import { NextResponse, type NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { SECTION_LABELS, type SectionType } from '@/types'

const EXPORT_ORDER: SectionType[] = [
  'executive_summary', 'problem_statement', 'target_users',
  'features_mvp', 'features_v2', 'user_stories',
  'system_architecture', 'data_model', 'api_design',
  'security', 'performance', 'error_handling',
  'deployment', 'testing', 'roadmap',
  'open_questions', 'sanity_check', 'next_steps',
]

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const { searchParams } = new URL(req.url)
  const format = searchParams.get('format') ?? 'markdown'

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  const { data: idea } = await supabase.from('ideas').select('*').eq('id', id).is('deleted_at', null).single()
  if (!idea) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  if (idea.visibility === 'private' && idea.user_id !== user?.id) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { data: sections } = await supabase.from('trd_sections').select('*').eq('idea_id', id)
  const { data: questions } = await supabase.from('questions').select('*').eq('idea_id', id)
  const { data: flowcharts } = await supabase
    .from('flowcharts').select('*').eq('idea_id', id).order('version', { ascending: false }).limit(1)

  const sectionMap = Object.fromEntries((sections ?? []).map((s) => [s.type, s]))

  // Build markdown
  const lines: string[] = [
    `# ${idea.title} — Technical Requirements Document`,
    ``,
    `> Generated by IdeaForge | ${new Date(idea.created_at).toLocaleDateString()} | ${idea.iteration_count} iteration(s) | ${idea.duration_minutes} min run`,
    ``,
    `---`,
    ``,
  ]

  for (const sectionType of EXPORT_ORDER) {
    const section = sectionMap[sectionType]
    if (!section) continue
    lines.push(`## ${SECTION_LABELS[sectionType]}`)
    lines.push(``)
    lines.push(section.content)
    lines.push(``)
    lines.push(`---`)
    lines.push(``)
  }

  // Flowchart
  const flowchart = flowcharts?.[0]
  if (flowchart) {
    lines.push(`## System Flowchart`)
    lines.push(``)
    lines.push('```mermaid')
    lines.push(flowchart.mermaid_source)
    lines.push('```')
    lines.push(``)
    lines.push(`---`)
    lines.push(``)
  }

  // Q&A log
  const answered = (questions ?? []).filter((q) => q.answer_text || q.auto_assumed)
  if (answered.length > 0) {
    lines.push(`## Clarifications & Assumptions`)
    lines.push(``)
    for (const q of answered) {
      lines.push(`**Q:** ${q.question_text}`)
      if (q.auto_assumed) {
        lines.push(`**A (assumed):** ${q.auto_assumption}`)
      } else {
        lines.push(`**A:** ${q.answer_text}`)
      }
      lines.push(``)
    }
    lines.push(`---`)
    lines.push(``)
  }

  const markdown = lines.join('\n')

  if (format === 'claude') {
    const claudePrompt = [
      `# CONTEXT FOR CLAUDE CODE`,
      `# This TRD was generated by IdeaForge over ${idea.duration_minutes} minutes.`,
      `# Paste this entire document into Claude Code, then say:`,
      `# "Let's start Phase 1. Set up the project structure and database schema."`,
      ``,
      `---`,
      ``,
      markdown,
      ``,
      `---`,
      ``,
      `# SUGGESTED STARTING POINT`,
      `Now that you have the full TRD, help me start building by:`,
      `1. Setting up a Next.js 15 project with TypeScript and Tailwind`,
      `2. Creating the Supabase project and applying the data model from the TRD`,
      `3. Building the first working screen: idea submission form`,
    ].join('\n')

    return NextResponse.json({ prompt: claudePrompt, markdown })
  }

  return new NextResponse(markdown, {
    headers: {
      'Content-Type': 'text/markdown',
      'Content-Disposition': `attachment; filename="${idea.title.replace(/[^a-z0-9]/gi, '_')}_TRD.md"`,
    },
  })
}
